#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#

source /opt/ros/indigo/setup.zsh
source ~/catkin_ws/devel/setup.zsh

export PATH=$PATH:~/bin/

alias vi='nvim'
export EDITOR='nvim'
export ROS_WORKSPACE='/home/daikimaekawa/catkin_ws'
